name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
        - 'v*'
      
jobs:
  build-project:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'
      - run: flutter --version

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Install dependencies
        run: flutter pub get
      
      # Run Flutter Build for APKs
      - name: Build Android APK
        run: flutter build apk --split-per-abi --dart-define=PURCHASE_CODE=${{ secrets.PURCHASE_CODE }}

      - name: Build Flutter Web
        run: flutter build web --release --no-tree-shake-icons --dart-define=PURCHASE_CODE=${{ secrets.PURCHASE_CODE }}

      - name: Archive Web
        uses: thedoctor0/zip-release@0.7.5
        with:
          directory: ./build/web/
          filename: web.zip

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            ./build/web/web.zip
            ./build/app/outputs/flutter-apk/


  # Release Project
  release-build-files:
    name: Publish Build Files
    runs-on: ubuntu-latest
    needs: build-project

    steps:
    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: build-files

    - name: Test Downloaded Files
      run: ls -R

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # tag_name: ${{ github.ref }}
        name: "Release for ${{ github.ref_name }}"
        files: |
          web/web.zip
          app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          app/outputs/flutter-apk/app-arm64-v8a-release.apk
          app/outputs/flutter-apk/app-x86_64-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}